apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    purpose: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: dev
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  type: loadBalancer
  selector:
    app: nginx
    tier: frontend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
   
  