apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static-demo
spec:
  containers:
  - name: myappnginx
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
     
  volumes:
   - name: persistent-storage
     persistentVolumeClaim:
        claimName: ebs-static
  ---
  kind: Service
  apiVersion: v1
  metadata:
    name: nginx-lb
  spec:
   type: LoadBalancer

      selector:
        purpose: ebs-static-demo
      ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30001
      